version: '3.9'

networks:
 default:
  name: 'records'

volumes: 
 record-logs: 
    
services:

 opensearch:
  container_name: 'record-os'
  image: 'opensearchproject/opensearch:2'
  ports: 
   - "9200:9200"
   - "9600:9600"
  environment:
   discovery.type: single-node
   plugins.security.disabled: 'true'
   OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Ssmsqwert123!"
   volumes:
    'record-logs:/usr/share/opensaerch/data'


    
 opensearch-dashboards:
  container_name: 'record-osd'
  image: 'opensearchproject/opensearch-dashboards:latest'
  ports: 
   - "5601:5601"
  environment:
   OPENSEARCH_HOSTS: '["http://record-os:9200"]'
   DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
  depends_on:
   - opensearch